import Foundation

enum MockJDIntelligence {
    static let entries: [JDEntry] = [
        JDEntry(
            id: "mock_jd_li_auto_wm",
            company: "Li Auto",
            teamOrDepartment: "World Model Team",
            roleTitle: "Research Engineer - 4D Reconstruction / World Model",
            city: "Beijing",
            sourceType: "manual_note",
            sourceName: "mock",
            sourceURL: nil,
            recordDate: "2026-07-21",
            jdText: "Responsible for autonomous driving world model, 4D reconstruction, 3DGS/4DGS, simulation generation, and PyTorch training.",
            recruiterContext: "Mock recruiter note: research engineering role, not a TPM role.",
            notes: "High signal JD for the current 4D reconstruction and WM decision plan.",
            mustHaveSkills: ["3DGS", "4DGS", "PyTorch", "autonomous driving"],
            bonusSkills: ["World Model", "driving video generation", "nuScenes"],
            newKeywords: ["dynamic gaussian", "world model"],
            salaryRange: "35-60K",
            salaryMinK: 35,
            salaryMaxK: 60,
            salaryMonths: "16",
            equity: "options",
            educationRequirement: "Master preferred",
            majorRequirement: "CS / Automation / Robotics",
            experienceYears: "3-6 years",
            paperOrPatentRequirement: "bonus",
            domainExperienceRequirement: "autonomous driving preferred",
            roleOrientation: "research_engineering",
            acceptsTransition: "yes",
            languageOrOverseasRequirement: "",
            monthChange: "new",
            personalGapAssessment: "Strong localization/SLAM base; need WM pipeline evidence.",
            applicationPriority: "high",
            status: "favorite",
            createdAt: Date(),
            updatedAt: Date()
        ),
        JDEntry(
            id: "mock_jd_robotics_reconstruction",
            company: "Unitree",
            teamOrDepartment: "Perception Algorithm",
            roleTitle: "Dynamic Scene Reconstruction Engineer",
            city: "Hangzhou",
            sourceType: "manual_note",
            sourceName: "mock",
            sourceURL: nil,
            recordDate: "2026-07-21",
            jdText: "Work on robotics dynamic scene reconstruction, point cloud processing, 3DGS, SLAM, and ROS integration.",
            recruiterContext: "",
            notes: "Embodied intelligence reconstruction signal.",
            mustHaveSkills: ["point cloud", "3DGS", "SLAM"],
            bonusSkills: ["ROS2", "robotics"],
            newKeywords: ["embodied reconstruction"],
            salaryRange: "25-45K",
            salaryMinK: 25,
            salaryMaxK: 45,
            salaryMonths: "14",
            equity: "options",
            educationRequirement: "Bachelor or above",
            majorRequirement: "Robotics / Automation",
            experienceYears: "2-5 years",
            paperOrPatentRequirement: "not required",
            domainExperienceRequirement: "robotics or AD",
            roleOrientation: "engineering",
            acceptsTransition: "yes",
            languageOrOverseasRequirement: "",
            monthChange: "new",
            personalGapAssessment: "ROS needs refresh; reconstruction direction is aligned.",
            applicationPriority: "medium",
            status: "watching",
            createdAt: Date(),
            updatedAt: Date()
        ),
    ]

    static let actions: [CandidateAction] = [
        CandidateAction(
            id: "mock_action_wm_demo",
            sourceJDIDs: ["mock_jd_li_auto_wm"],
            sourceAnalysisIDs: ["mock_analysis_wm"],
            relatedSkillIDs: ["skill_world_model_generation"],
            relatedTaskIDs: ["task_world_model_entry"],
            actionType: "run_experiment",
            title: "Run one lightweight driving video generation demo",
            reason: "Several high-interest JDs ask for WM / generation evidence, while your current plan already has Week 9-10 reserved for WM pipeline entry.",
            expectedOutput: "A runnable demo note with input/output form, generated video, and limitations.",
            effortEstimateMin: 120,
            priority: "high",
            timeSensitivity: "this_month",
            risk: "Do not interrupt the current reconstruction wrap-up.",
            suggestedSlot: "Week 9-10 WM pipeline slot",
            status: "suggested",
            userDecisionReason: "",
            convertedTaskID: nil,
            createdAt: Date(),
            updatedAt: Date()
        ),
        CandidateAction(
            id: "mock_action_resume_4dgs",
            sourceJDIDs: ["mock_jd_li_auto_wm", "mock_jd_robotics_reconstruction"],
            sourceAnalysisIDs: ["mock_analysis_wm"],
            relatedSkillIDs: ["skill_4dgs_dynamic_reconstruction"],
            relatedTaskIDs: ["task_reconstruction_wrap_up"],
            actionType: "update_resume",
            title: "Add SLAM x 4DGS reconstruction evidence to resume material",
            reason: "The market signal is useful only if your resume can show visible reconstruction evidence, not only localization history.",
            expectedOutput: "One project bullet, one metric/video evidence note, and one interview story.",
            effortEstimateMin: 45,
            priority: "medium",
            timeSensitivity: "this_month",
            risk: "",
            suggestedSlot: "Wednesday JD follow-up",
            status: "suggested",
            userDecisionReason: "",
            convertedTaskID: nil,
            createdAt: Date(),
            updatedAt: Date()
        ),
    ]

    static let skillSnapshot = SkillStackSnapshot(
        id: "mock_skill_snapshot",
        createdAt: Date(),
        summary: "Mock capability snapshot seeded from current AGENTS context.",
        skills: [
            SkillProfile(
                id: "skill_slam",
                name: "SLAM Geometric Consistency",
                category: "slam",
                level: "solid",
                confidence: "high",
                evidence: ["SLAM theory and autonomous-driving localization architecture"],
                relatedProjects: ["SLAM-enhanced 4DGS"],
                lastPracticedAt: nil,
                targetLevel: "strong",
                gapNotes: "Need to connect geometry advantage to reconstruction evidence.",
                priority: "high"
            ),
            SkillProfile(
                id: "skill_world_model",
                name: "World Model / Driving Video Generation",
                category: "world_model",
                level: "beginner",
                confidence: "medium",
                evidence: ["Planned Week 9-10 pipeline entry"],
                relatedProjects: ["nuScenes WM pipeline"],
                lastPracticedAt: nil,
                targetLevel: "working",
                gapNotes: "Need one runnable lightweight pipeline and notes on input-output form.",
                priority: "high"
            ),
        ]
    )

    static let taskSnapshot = TaskStateSnapshot(
        id: "mock_task_snapshot",
        createdAt: Date(),
        currentPhase: "Week 7-12 decision plan",
        summary: "Reconstruction line is active; WM line is planned after evidence is produced.",
        tasks: [
            TaskProfile(
                id: "task_reconstruction_wrap_up",
                title: "Week 7-8 Reconstruction Wrap-up",
                category: "reconstruction_line",
                status: "active",
                currentPhase: "StreetGaussian / 4DGS on nuScenes",
                relatedSkillIDs: ["skill_slam", "skill_4dgs"],
                deadline: nil,
                weeklySlot: "current main line",
                progressSummary: "Need baseline, comparison videos, and metric table.",
                blockers: [],
                nextMilestone: "GT-box vs SLAM filtering comparison",
                evidenceOutputs: ["comparison video", "metric table"],
                adjustability: "low"
            ),
            TaskProfile(
                id: "task_world_model_entry",
                title: "Week 9-10 World Model Pipeline Entry",
                category: "world_model_line",
                status: "planned",
                currentPhase: "candidate model selection",
                relatedSkillIDs: ["skill_world_model"],
                deadline: nil,
                weeklySlot: "after reconstruction wrap-up",
                progressSummary: "Not started.",
                blockers: [],
                nextMilestone: "Run one lightweight driving video generation demo",
                evidenceOutputs: ["generated video", "input-output notes"],
                adjustability: "medium"
            ),
        ]
    )
}
