from datetime import datetime, timezone
from typing import List, Optional
from uuid import uuid4

from app.db.repositories import ChatRepository, SessionRepository
from app.schemas.chat import (
    AIChatMessage,
    AIChatSendResponse,
    AIChatSummary,
    AIChatThread,
    AIChatThreadCreate,
    ChatRole,
)
from app.services.llm_service import MockLLMService


class ChatService:
    def __init__(self) -> None:
        self.chats = ChatRepository()
        self.sessions = SessionRepository()
        self.llm = MockLLMService()

    def create_thread(self, request: AIChatThreadCreate) -> Optional[AIChatThread]:
        session = self.sessions.get_by_id(request.session_id)
        if session is None:
            return None
        now = datetime.now(timezone.utc)
        thread = AIChatThread(
            id=session.ai_chat_thread_id or f"chat_{uuid4().hex[:12]}",
            session_id=session.id,
            task_type=session.task_type,
            context_refs=request.context_refs,
            messages=[],
            created_at=now,
            updated_at=now,
        )
        return self.chats.save_thread(thread)

    def get_thread(self, thread_id: str) -> Optional[AIChatThread]:
        return self.chats.get_thread(thread_id)

    def get_threads_by_session(self, session_id: str) -> List[AIChatThread]:
        return self.chats.get_by_session(session_id)

    def send_message(self, thread_id: str, content: str) -> Optional[AIChatSendResponse]:
        thread = self.chats.get_thread(thread_id)
        if thread is None:
            return None
        now = datetime.now(timezone.utc)
        user_message = AIChatMessage(
            id=f"msg_{uuid4().hex[:12]}",
            role=ChatRole.user,
            content=content,
            created_at=now,
        )
        assistant_message = AIChatMessage(
            id=f"msg_{uuid4().hex[:12]}",
            role=ChatRole.assistant,
            content=self.llm.reply(thread.task_type, content),
            created_at=datetime.now(timezone.utc),
        )
        updated_thread = thread.model_copy(
            update={
                "messages": thread.messages + [user_message, assistant_message],
                "updated_at": datetime.now(timezone.utc),
            }
        )
        self.chats.save_thread(updated_thread)
        return AIChatSendResponse(
            thread=updated_thread,
            user_message=user_message,
            assistant_message=assistant_message,
        )

    def summarize_thread(self, thread_id: str) -> Optional[AIChatSummary]:
        thread = self.chats.get_thread(thread_id)
        if thread is None:
            return None

        user_messages = [message.content for message in thread.messages if message.role == ChatRole.user]
        assistant_messages = [
            message.content for message in thread.messages if message.role == ChatRole.assistant
        ]

        latest_user = user_messages[-1] if user_messages else "No user question yet."
        latest_assistant = assistant_messages[-1] if assistant_messages else "No agent answer yet."
        context_label = ", ".join(thread.context_refs) if thread.context_refs else "current material"

        return AIChatSummary(
            thread_id=thread.id,
            session_id=thread.session_id,
            suggested_title=f"Discussion note: {thread.task_type.value}",
            summary=(
                "Mock summary: discussed the current material with the Agent. "
                f"Context: {context_label}. Main user question: {latest_user}"
            ),
            key_insights=[
                f"Agent response to keep: {latest_assistant}",
                "This note is generated by the mock summarizer and can be edited before saving.",
            ],
            action_items=[
                "Review whether this discussion changes the current study or tracking plan.",
                "Replace the mock summarizer with an LLM-backed summarizer later.",
            ],
            context_refs=thread.context_refs,
        )
